swagger: '2.0'
info:
  version: beta
  title: Customer Survey Events
  description: 'Events described here tell you what happens to **surveys** and **survey templates**. To learn more about general approach to event processing see [How to work with events]().'
host: playground.apistudio.io
basePath: /try/86501cfa-c99e-4d69-8236-d9fcf41bba7d
schemes:
  - http
produces:
  - application/json
paths:
  /survey-captured:
    get:
      summary: A new survey is captured and recorded
      tags:
        - Surveys
      responses:
        '200':
          description: Event payload
          schema:
            $ref: '#/definitions/survey-captured'
definitions:
  event:
    x-asse-comment: Event is redefined within each API to provide more specific examples and documentation
    type: object
    discriminator: kind
    required:
      - kind
    properties:
      kind:
        type: string
        description: Unique kind of event
        enum:
          - survey-captured
      occurred-on:
        type: string
        format: date-time
        description: Time when an event occurred
      id:
        type: string
        format: uuid
        description: Unique identifier of event instance in UUID format
    example:
      kind: survey-captured
      occurred-on: '2015-11-19T13:21:01.000Z'
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
  survey-captured:
    type: object
    description: A new survey was captured
    allOf:
      - $ref: '#/definitions/event'
      - type: object
        properties:
          path:
            type: string
    example:
      kind: survey-captured
      id: 736a07bd-809e-43bd-9ac1-20991a78f390
