swagger: '2.0'
basePath: "/fraud-detection"
schemes:
  - http
host: api.asee.co

info:
  title: Fraud Detection API
  version: beta
  description: |
     Fraud Detection API enables to prevent fraud activitis according to legal requirements of financial institution.
     With Fraud Detection API you can:
       - Check client AML status 
       - Check whether client is on black list.
    
tags:
  -
    name: AML
    description: Working with AML lists
  -
    name: Black lists
    description: Working with Black lists

responses:
  default-error-response:
    description: Besides specific status codes above, other standard http [status codes](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) can be returned for each request. To learn more see general guidance on [error handling]()
    
  
paths:
  "/aml/status":
    get:
      operationId: AML_GetStatus
      parameters:
      - description: Personal identification number (JMBG).
        in: query
        name: personal-identification-number
        required: true
        type: string
      - description: First name of the client.
        in: query
        name: first-name
        required: true
        type: string
      - description: Last name of the client.
        in: query
        name: last-name
        required: true
        type: string
      - description: City where the client lives.
        in: query
        name: city
        required: false
        type: string
      - description: Country code.
        in: query
        name: country-code
        required: false
        type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/aml-status'          
        default:
          $ref: '#/responses/default-error-response'  
      summary: Checks customer AML status and returns customer rating and reliability.
      tags:
        - AML
  "/black-lists/status":
    get:
      operationId: BlackLists_GetStatus
      parameters:
      - description: Personal identification number (JMBG).
        in: query
        name: personal-identification-number
        required: true
        type: string
      - description: First name of the client.
        in: query
        name: first-name
        required: true
        type: string
      - description: Last name of the client.
        in: query
        name: last-name
        required: true
        type: string
      - description: City where the client lives.
        in: query
        name: city
        required: false
        type: string
      - description: Country code.
        in: query
        name: country-code
        required: false
        type: string
      responses:
        '200':
          description: Success
          schema:
              items:
                $ref: '#/definitions/black-list-status' 
              type: array
        default:
          $ref: '#/responses/default-error-response'  
      summary: Checks whether client is on black lists and returns percentages of belonging.
      tags:
        - Black lists
    
definitions:

  aml-status: 
      description: Indicates the AML rating of a customer.
      properties: 
        rating-value: 
          x-asee-compliance: Is there some correlation between this property and the one below? Five vs four values in enumeration.
          description: The evaluation of the acceptability of the customer. Possible values are in range [0-4]
          type: "string"
          enum: 
          - 0
          - 1
          - 2
          - 3
          - 4
        reliability: 
          description: The presumed accuracy of the assessment result.
          type: "string"
          enum: 
          - low-risk
          - normal-risk
          - high-risk
          - unacceptable-risk
      type: "object"  
      example:
        rating-value: 0
        reliability: low-risk
  black-list-status: 
      description: Indicates the affiliation of a customer to black list.
      properties: 
        percentage: 
          description: Percent of matching.
          type: "string"
        name: 
          description: Name of black list on which client was found.
          type: "string"
      type: "object"    
      example:
        items:
          - 
           percentage: 80
           name: EU black list
          - 
           percentage: 75
           name: UN black list
