swagger: '2.0'
x-asee-visibility: public
info:
  description: Authorization API enables authorization of sensitive actions performed by customers or agents using 2nd factor authentication. Sensitive action authorizations can be explicitly requested by applications or they can be initiated by APIs during authorization checking. Support for 4 eyes verification and separation of duties will be added in future.
  title: Authorization API
  version: v1
host: bankapi.net
basePath: /v1/authorization
tags:
  - description: Working with one-time passwords
    name: OTP
consumes:
  - application/json
produces:
  - application/json
schemes:
  - https
  - http
paths:
  /otp/sms/send:
    post:
      summary: Generate and send SMS one-time password
      description: Generates one-time password and sends it to receipient specified in `user-id` or `phone-number`
      tags:
        - OTP
      x-asee-tags: []
      operationId: OTP_SendSMS
      parameters:
        - description: Command with details to send SMS OTP
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/send-sms-otp-command'
      responses:
        202:
          description: Accepted - SMS sent
          schema:
            $ref: '#/definitions/verification-id'
        440:
          description: |
            Your request was well constructed but it could not be processed. Consider the following possible problems and look into response for more details:

            - [no-such-user]()
        default:
          $ref: '#/responses/default-error-response'

  /otp/sms/verify:
    post:
      operationId: OTP_VerifySMS
      summary: Verify SMS one-time password
      description: Verifies one-time password entered by user for verification in progress
      tags:
        - OTP
      x-asee-tags: []
      parameters:
        - description: Request with details to verify SMS OTP
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/verify-sms-otp-request'
      responses:
        204:
          description: No content - OTP is valid
        440:
          description: |
            Your request was well constructed but OTP was be verified. Consider the following possible problems and look into response for more details:

            - [bad-otp]()
            - [replayed-otp]()
            - [no-such-verification]()
        default:
          $ref: '#/responses/default-error-response'

  /otp/email/send:
    post:
      summary: Generate and send email with one-time password
      description: Generates one-time password and sends it to receipient specified in `user-id` or `email`
      tags:
        - OTP
      x-asee-tags: []
      operationId: OTP_SendEmail
      parameters:
        - description: Command with details to send OTP email
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/send-email-otp-command'
      responses:
        202:
          description: Accepted - Email sent
          schema:
            $ref: '#/definitions/verification-id'
        440:
          description: |
            Your request was well constructed but it could not be processed. Consider the following possible problems and look into response for more details:

            - [no-such-user]()
        default:
          $ref: '#/responses/default-error-response'

  /otp/email/verify:
    post:
      operationId: OTP_VerifyEmail
      summary: Verify email one-time password
      description: Verifies one-time password entered by user for verification in progress
      tags:
        - OTP
      x-asee-tags: []
      parameters:
        - description: Request with details to verify email OTP
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/verify-email-otp-request'
      responses:
        204:
          description: No content - OTP is valid
        440:
          description: |
            Your request was well constructed but OTP coul not be verified. Consider the following possible problems and look into response for more details:

            - [bad-otp]()
            - [replayed-otp]()
            - [no-such-verification]()
        default:
          $ref: '#/responses/default-error-response'

  /otp/oath/verify:
    post:
      operationId: OTP_VerifyOATH
      summary: Verify OATH compliant one-time password
      description: Verifies TOTP or HOTP one-time password entered by user identified with `user-id`
      tags:
        - OTP
      x-asee-tags: []
      parameters:
        - description: Request with details to verify HOTP or TOTP
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/verify-oath-otp-request'
      responses:
        204:
          description: No content - OTP is valid
        440:
          description: |
            Your request was well constructed but OTP could not be verified. Consider the following possible problems and look into response for more details:

            - [bad-otp]()
            - [replayed-otp]()
            - [no-such-user]()
          schema:
            $ref: '#/definitions/business-problem'
        default:
          $ref: '#/responses/default-error-response'

  /ocra/challenge:
    post:
      operationId: OCRA_GenerateChallenge
      summary: Generate OCRA challenge
      description: Generates OCRA challenge based on optional data for signature provided by application or random seed
      tags:
        - OCRA
      x-asee-tags: []
      parameters:
        - description: Request with details to generate OCRA challenge
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/generate-ocra-challenge-request'
      responses:
        200:
          description: OK - OCRA challenge generated
          schema:
            $ref: '#/definitions/challenge'          
        440:
          description: |
            Your request was well constructed but OCRA challenge could not be generated. Consider the following possible problems and look into response for more details:

            - [no-such-user]()
          schema:
            $ref: '#/definitions/business-problem'
        default:
          $ref: '#/responses/default-error-response'
                    
  /ocra/verify:
    post:
      operationId: OCRA_VerifyResponse
      summary: Verify OCRA response
      description: Verifies OCRA response to previously generated challenge
      tags:
        - OCRA
      x-asee-tags: []
      parameters:
        - description: Request with details to verify OCRA response
          in: body
          name: cmd
          required: true
          schema:
            $ref: '#/definitions/verify-ocra-response-request'
      responses:
        204:
          description: No content - OCRA response is valid
        440:
          description: |
            Your request was well constructed but OCRA response could not be verified. Consider the following possible problems and look into response for more details:

            - [bad-response]()
            - [replayed-response]()
            - [no-such-challenge]()
          schema:
            $ref: '#/definitions/business-problem'
        default:
          $ref: '#/responses/default-error-response'
          
parameters: {}
definitions:

  business-problem:
    description: Details on specific problem that prevented processing after successfull validation
    type: object
    example:
      problem: document-locked
      message: Document you are trying to access is locked by another user
      details: User john.doe has locked the document
    properties:
      problem:
        description: Unique literal that identifies specific problem
        type: string
      message:
        description: Message explaining the situation and optionaly remedies
        type: string
      details:
        description: Optional details supplied for troubleshooting
        type: string

  send-sms-otp-command:
    description: Command with details to send SMS OTP
    properties:
      action:
        type: string
        description: Optional service code of sensitive action that will be verified
      message:
        type: string
        description: Optional message to include in SMS sent to user
      phone-number:
        type: string
        format: phone
        description: Phone number that will receive OTP
      user-id:
        type: string
        description: Optional identifier of user who will receive SMS on preferred mobile phone number.
    example:
      action: auth-01
      message: authentication
      phone-number: "+38165222333"
      user-id: test.user

  send-email-otp-command:
    description: Command with details to send email OTP
    properties:
      action:
        type: string
        description: Optional service code of sensitive action that will be verified
      message:
        type: string
        description: Optional message to include in SMS sent to user
      email:
        type: string
        format: email
        description: Email that will receive OTP
      user-id:
        type: string
        description: Optional identifier of user who will receive SMS on preferred mobile phone number.
    example:
      action: auth-01
      message: authentication
      email: "test.user@mybank.com"
      user-id: test.user

  verification-id:
    description: Identifies SMS OTP verification in progress
    type: string
    example: "2112"

  verify-sms-otp-request:
    description: Request with details to verify SMS OTP
    properties:
      verification-id:
        description: Identifies SMS OTP verification in progress
        type: string
      otp:
        type: string
        description: Digits sent via SMS
    example:
      verification-id: "21123456"
      otp: "1234"

  verify-email-otp-request:
    description: Request with details to verify Email OTP
    properties:
      verification-id:
        description: Identifies SMS OTP verification in progress
        type: string
      otp:
        type: string
        description: Digits sent via Email
    example:
      verification-id: "21123456"
      otp: "123456"

  verify-oath-otp-request:
    description: Request with details to verify HOTP or TOTP
    required:
      - user-id
      - otp
    properties:
      user-id:
        type: string
        description: For existing user (customer or agent)
      otp:
        type: string
        description: Digits generated by HOTP or TOTP
    example:
      user-id: "test.user"
      otp: "123456"

  generate-ocra-challenge-request:
    description: Request with details to generate OCRA challenge
    properties:
      challenge-mode:
        type: string
        description: One of the supported OCRA modes for challenge
        enum: [signature, random]
      signature-data:
        type: string
        description: Data to be signed provided by application as a reference to transaction. Used only with signature mode of challenge.
      user-id:
        type: string
        description: Identifier of user whose secret will be used to generate challenge
    example:
      challenge-mode: signature
      signature-data: 1601231231231231|12000.00RSD
      user-id: test.user
  
  challenge:
    description: Challenge data generated
    properties:
      challenge-id:
        description: Identifies challenge in progress for which response will be verified 
        type: string
      challenge-code:
        type: string
        description: Digits generated as challenge code
    example:
      challenge-id: "21123422"
      challenge-code: "78778718"
  
  verify-ocra-response-request:
    description: Request with details to verify OCRA response
    properties:
      challenge-id:
        description: Identifies challenge in progress for which response is verified 
        type: string
      response-code:
        type: string
        description: Digits entered as response
    example:
      challenge-id: "21123456"
      response-code: "123456"

responses:
  default-error-response:
    description: 'Besides specific status codes above, other standard http [status codes](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) can be returned for each request. To learn more see general guidance on [error handling](common-getstarted.html#error-handling)'
