swagger: '2.0'
x-asee-visibility: internal
basePath: /beta/fraud
schemes:
  - http
  - https
host: bankapi.net

info:
  title: Fraud API
  version: beta
  description: Fraud API helps detect fraudelent and money laundering activities by checking persons against AML lists and blacklists according to legal requirements.

tags:
  -
    name: AML
    description: Working with AML lists
  -
    name: Blacklist
    description: Working with Blacklists

responses:
  default-error-response:
    description: Besides specific status codes above, other standard http [status codes](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) can be returned for each request. To learn more see general guidance on [error handling]()

paths:
  "/aml/check":
    get:
      operationId: AML_Check
      summary: Checks person against AML lists
      description: Checks person identity against anti money laundering (AML) person list and returns match rating and reliability
      parameters:
      - description: Identification number available (national-id-number, SSN, passport number or similar)
        in: query
        name: identification-number
        required: true
        type: string
      - description: First name of the person
        in: query
        name: first-name
        required: true
        type: string
      - description: Last name of the person
        in: query
        name: last-name
        required: true
        type: string
      - description: City where the person lives
        in: query
        name: city
        required: false
        type: string
      - description: ISO 3166-2 country code
        in: query
        name: country
        required: false
        type: string
        format: ISO 3166-2
        minLength: 2
        maxLength: 2
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/aml-status'
        default:
          $ref: '#/responses/default-error-response'

      tags:
        - AML

  "/blacklist/check":
    get:
      operationId: BlackList_Check
      summary: Checks person against blacklists
      description: Checks person identity against black list and returns match rating and reliability
      parameters:
      - description: Identification number available (national-id-number, SSN, passport number or similar)
        in: query
        name: identification-number
        required: true
        type: string
      - description: First name of the person
        in: query
        name: first-name
        required: true
        type: string
      - description: Last name of the person
        in: query
        name: last-name
        required: true
        type: string
      - description: City where the person lives
        in: query
        name: city
        required: false
        type: string
      - description: ISO 3166-2 country code
        in: query
        name: country
        required: false
        type: string
        format: ISO 3166-2
        minLength: 2
        maxLength: 2
      responses:
        '200':
          description: Success
          schema:
              items:
                $ref: '#/definitions/blacklist-status'
              type: array
        default:
          $ref: '#/responses/default-error-response'
      tags:
        - Blacklist

definitions:

  aml-status:
    description: AML rating of a person
    properties:
      rating:
        description: The evaluation of the acceptability of the person as a customer. Possible values are in range [0-4]
        type: integer
        format: int32
        minimum: 0
        maximum: 4
      reliability:
        description: |
          The presumed accuracy of the assessment result
          For a list of possible values see [reliabilities](fraud-classifications.html#reliabilities) enumeration.
        type: string
        enum:
        - low-risk
        - normal-risk
        - high-risk
        - unacceptable-risk
        x-asee-enumeration: reliabilities
    example:
      rating-value: 0
      reliability: low-risk

  blacklist-match:
    properties:
      percentage:
        description: Likelihood of match as percentage
        type: number
        format: double
        minimum: 0
        maximum: 100
      name:
        description: Name of blacklist against where match was found
        type: "string"
  blacklist-status:
    description: Lists of matches against different blacklists
    properties:
      matches:
        type: array
        items:
          $ref: '#/definitions/blacklist-match'
    example:
      matches:
        -
         likelihood: 80
         name: EU blacklist
        -
         likelihood: 75
         name: UN blacklist
